PBAK API.http


@baseUrl = https://cc053e298e39.ngrok-free.app/api/v1
@apiKey = nokey
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzYzNDUwNjk0LCJleHAiOjE3NjM1MzcwOTR9.eo0_oOfmRx0ZYk93pqy_SustQM9Rd9pm3vayL67_WJ0
@contentType = application/json

### Health check
GET {{baseUrl}}/
Content-Type: {{contentType}}

### register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}
x-api-key: {{apiKey}}

{
  "email": "evahnce@live.com",
  "password": "Abc@1234",
  "phone" : "+254721374510",
  "alternative_phone" : "+254721374510",
  "first_name" : "Evanson",
  "last_name" : "Kuria",
  "date_of_birth" :  "1986-01-01",
  "gender" : "male",
  "national_id" : "1234235436",
  "driving_license_number" : "123522436",
  "dl_pic" : 1,
  "passport_photo" : 1,
  "occupation":1,
  "estate_id":1,
  "road_name" : "", 
  "club_id" : 1
}

### login admin
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}
x-api-key: {{apiKey}}

{
  "email": "admin@pbak.com",
  "password": "Admin@123"

}


### login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}
x-api-key: {{apiKey}}

{
  "email": "evahnce@live.com",
  "password": "Abc@1234" 
}



### List available members
GET {{baseUrl}}/members
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

### member stats
GET {{baseUrl}}/members/stats
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}


### get member by id
GET {{baseUrl}}/members/2
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}


### update member medical details by id.
### Any provided value will be updated. even if only one element is sent
PUT {{baseUrl}}/members/2/
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

{
  "emergency_contact" : "Evans",
  "blood_type" : "O+",
  "allergies" : "None",
  "medical_policy_no" : "",
  "interest_medical" : 1,
  "interest_legal_support" : 1,
  "interest_member_welfare" : 1,
  "interest_safety_workshops" : 1, 
  "interest_cert_train" : 1,
  "interest_biker_advocacy" : 1,
  "interest_association" : 1,
  "interest_safety_training" : 1,
  "interest_training_updates" : 1,
  "tier_id" :  1,
}

### get clubs
GET {{baseUrl}}/params/clubs
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}


### get counties
GET {{baseUrl}}/params/regions
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}


### get towns
GET {{baseUrl}}/params/regions/47
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

### get estates
GET {{baseUrl}}/params/regions/47/1
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}


### get bike makes
GET {{baseUrl}}/bikes/makes
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}


### get bike models
GET {{baseUrl}}/bikes/models/1
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

### get bikes
GET {{baseUrl}}/bikes
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

### get bike by ID
GET {{baseUrl}}/bikes/1
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

### create bike
POST {{baseUrl}}/bikes
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

{
      "model_id" :1,
      "registration_number" :"KBV374Q",
      "chassis_number" : "1232143245",
      "engine_number" :"2342144",
      "color" : "SILVER",
      "purchase_date" :"2015-01-01",
      "registration_date" : "2015-01-01",
      "registration_expiry" : "2016-01-01",
      "bike_photo_url":"BIKE/PH12313.JPG",
      "odometer_reading" :"321432314",
      "insurance_expiry" : "2017-01-01",
      "is_primary" :  true  ,
      "yom" : "2015-01-01",
      "photo_front_id" : 1,
      "photo_side_id" : 1,
      "photo_rear_id" : 1,
      "insurance_logbook_id" : 1,
      "has_insurance": 1,
      "experience_years": 10,

}

### update bike
PUT {{baseUrl}}/bikes/1
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

{

      "color" : "SILVER",
      "registration_expiry" : "2016-01-01",
      "bike_photo_url":"BIKE/PH12313.JPG",
      "odometer_reading" :"321432314",
      "insurance_expiry" : "2017-01-01",
      "is_primary" :  true  ,
      "status" : "active" 
}



# ### sos
# POST {{baseUrl}}/sos
# Content-Type: {{contentType}}
# x-api-key: {{apiKey}}
# Authorization: {{token}}

# {
#       "lat": 12.0,
#       "lon": -11,
#       "mode" : "0", // auto, on request
#       "acc_change" : "56", // accelereometer change that triggerd
#       "bearing" : "23", // in defgrees
#       "notification_type" : 0, // 0 decleraete. 1 accelerate
#       "acc_val_before" : "12,89,12,5",
#       "acc_val_after" : "12,34,45,67"
# }


### sos
POST {{baseUrl}}/sos
Content-Type: {{contentType}}
x-api-key: {{apiKey}}
Authorization: {{token}}

{
      "lat": 12.0,
      "lon": -11,
      "mode" : "0",
      "acc_change" : "",
      "bearing" : "23",
      "notification_type" : 0, 
      "acc_val_before" : "12,89,12,5",
      "acc_val_after" : "12,34,45,67"
}



{"statusCode":200,"status":"success","rsp":true,"member_id":"31008472","registration_status":"CONFIRMED","has_pillion":false,"pillion_names":"","can_check_in":true,"member_name":"UAMKR
4MR46","has_add_ons":false,"add_ons":[]}