class MockData {
  static const List<Map<String, dynamic>> clubs = [
    {
      'id': '1',
      'name': 'Nairobi Riders',
      'region': 'Nairobi',
      'description': 'The premier motorcycle club in Nairobi, promoting safe riding and community engagement.',
      'logoUrl': null,
      'officials': [
        {'userId': '1', 'name': 'John Kamau', 'position': 'Chairman', 'photoUrl': null},
        {'userId': '2', 'name': 'Mary Wanjiru', 'position': 'Secretary', 'photoUrl': null},
        {'userId': '3', 'name': 'Peter Omondi', 'position': 'Treasurer', 'photoUrl': null},
      ],
      'memberCount': 145,
      'foundedDate': '2015-03-15T00:00:00.000Z',
      'meetingLocation': 'Uhuru Park',
      'contactEmail': 'info@nairobiriters.ke',
      'contactPhone': '+254712345678',
    },
    {
      'id': '2',
      'name': 'Mombasa Coastal Riders',
      'region': 'Mombasa',
      'description': 'Experience the thrill of coastal rides with Kenya\'s most vibrant riding community.',
      'logoUrl': null,
      'officials': [
        {'userId': '4', 'name': 'Hassan Ali', 'position': 'Chairman', 'photoUrl': null},
        {'userId': '5', 'name': 'Grace Mwangi', 'position': 'Secretary', 'photoUrl': null},
      ],
      'memberCount': 98,
      'foundedDate': '2016-07-20T00:00:00.000Z',
      'meetingLocation': 'Bamburi Beach',
      'contactEmail': 'coastal@riders.ke',
      'contactPhone': '+254722345678',
    },
    {
      'id': '3',
      'name': 'Rift Valley Riders',
      'region': 'Nakuru',
      'description': 'Exploring the scenic Rift Valley on two wheels.',
      'logoUrl': null,
      'officials': [
        {'userId': '6', 'name': 'David Kipchoge', 'position': 'Chairman', 'photoUrl': null},
      ],
      'memberCount': 67,
      'foundedDate': '2018-01-10T00:00:00.000Z',
      'meetingLocation': 'Lake Nakuru',
      'contactEmail': 'riftvalley@riders.ke',
      'contactPhone': '+254732345678',
    },
  ];

  static const List<Map<String, dynamic>> packages = [
    {
      'id': '1',
      'name': 'Basic Membership',
      'price': 2500.0,
      'durationDays': 365,
      'description': 'Essential membership benefits for all PBAK members',
      'benefits': [
        'PBAK Membership Card',
        'Access to Club Events',
        'Monthly Newsletter',
        'Basic Insurance Coverage',
        'Emergency Roadside Assistance',
      ],
      'addOns': [
        {'id': 'a1', 'name': 'Extra Insurance', 'price': 1500.0, 'description': 'Enhanced coverage'},
        {'id': 'a2', 'name': 'Premium Support', 'price': 800.0, 'description': '24/7 priority support'},
      ],
      'autoRenew': false,
      'iconUrl': null,
    },
    {
      'id': '2',
      'name': 'Premium Membership',
      'price': 5000.0,
      'durationDays': 365,
      'description': 'Premium benefits with exclusive perks',
      'benefits': [
        'All Basic Benefits',
        'Premium Insurance Coverage',
        'Free Event Tickets (up to 5)',
        'Discounted Service Rates',
        'Priority SOS Response',
        'Exclusive Merchandise',
      ],
      'addOns': [
        {'id': 'a3', 'name': 'International Coverage', 'price': 3000.0, 'description': 'Coverage in East Africa'},
      ],
      'autoRenew': true,
      'iconUrl': null,
    },
    {
      'id': '3',
      'name': 'Gold Membership',
      'price': 10000.0,
      'durationDays': 365,
      'description': 'The ultimate PBAK experience',
      'benefits': [
        'All Premium Benefits',
        'Comprehensive Insurance',
        'Unlimited Event Access',
        'Personal Riding Instructor',
        'VIP Club Access',
        'Annual Bike Service',
        'Exclusive Gold Card',
      ],
      'addOns': [],
      'autoRenew': true,
      'iconUrl': null,
    },
  ];

  static const List<Map<String, dynamic>> bikes = [
    {
      'id': '1',
      'userId': 'current_user',
      'make': 'Yamaha',
      'model': 'MT-07',
      'type': 'Sport',
      'registrationNumber': 'KBZ 456Y',
      'engineNumber': 'YMH789012',
      'year': 2022,
      'color': 'Blue',
      'imageUrl': null,
      'linkedPackageId': '1',
      'addedDate': '2023-01-15T00:00:00.000Z',
    },
    {
      'id': '2',
      'userId': 'current_user',
      'make': 'Honda',
      'model': 'CB500X',
      'type': 'Adventure',
      'registrationNumber': 'KCA 789X',
      'engineNumber': 'HND456789',
      'year': 2021,
      'color': 'Red',
      'imageUrl': null,
      'linkedPackageId': '2',
      'addedDate': '2023-03-20T00:00:00.000Z',
    },
  ];

  static const List<Map<String, dynamic>> insurance = [
    {
      'id': '1',
      'userId': 'current_user',
      'bikeId': '1',
      'type': 'Comprehensive',
      'provider': 'Jubilee Insurance',
      'price': 15000.0,
      'startDate': '2024-01-01T00:00:00.000Z',
      'endDate': '2024-12-31T23:59:59.000Z',
      'status': 'Active',
      'policyNumber': 'JUB2024001234',
      'documentUrl': null,
    },
    {
      'id': '2',
      'userId': 'current_user',
      'bikeId': '2',
      'type': 'Third Party',
      'provider': 'AAR Insurance',
      'price': 8000.0,
      'startDate': '2024-01-01T00:00:00.000Z',
      'endDate': '2024-12-31T23:59:59.000Z',
      'status': 'Active',
      'policyNumber': 'AAR2024005678',
      'documentUrl': null,
    },
  ];

  static const List<Map<String, dynamic>> events = [
    {
      'id': '1',
      'title': 'Nairobi City Ride',
      'description': 'A scenic ride through Nairobi\'s iconic landmarks. All riders welcome!',
      'dateTime': '2024-04-15T08:00:00.000Z',
      'location': 'Uhuru Park',
      'locationLatLng': '-1.2833,36.8167',
      'hostClubId': '1',
      'hostClubName': 'Nairobi Riders',
      'fee': 500.0,
      'maxAttendees': 50,
      'currentAttendees': 32,
      'type': 'Ride Out',
      'imageUrl': null,
      'attendeeIds': [],
    },
    {
      'id': '2',
      'title': 'Safety Training Workshop',
      'description': 'Learn essential riding safety techniques from certified instructors.',
      'dateTime': '2024-04-20T10:00:00.000Z',
      'location': 'PBAK Training Center, Thika Road',
      'locationLatLng': '-1.2195,36.8940',
      'hostClubId': '1',
      'hostClubName': 'Nairobi Riders',
      'fee': 1000.0,
      'maxAttendees': 30,
      'currentAttendees': 18,
      'type': 'Training',
      'imageUrl': null,
      'attendeeIds': [],
    },
    {
      'id': '3',
      'title': 'Coastal Charity Ride',
      'description': 'Join us for a charity ride along the beautiful Kenyan coast.',
      'dateTime': '2024-05-01T07:00:00.000Z',
      'location': 'Bamburi Beach',
      'locationLatLng': '-4.0435,39.7212',
      'hostClubId': '2',
      'hostClubName': 'Mombasa Coastal Riders',
      'fee': 1500.0,
      'maxAttendees': 100,
      'currentAttendees': 45,
      'type': 'Charity Event',
      'imageUrl': null,
      'attendeeIds': [],
    },
  ];

  static const List<Map<String, dynamic>> services = [
    {
      'id': '1',
      'name': 'Quick Fix Garage',
      'category': 'Mechanic',
      'description': 'Professional motorcycle repair and maintenance services',
      'location': 'Ngong Road, Nairobi',
      'latitude': -1.2921,
      'longitude': 36.7833,
      'contactPhone': '+254712345001',
      'contactEmail': 'info@quickfix.ke',
      'type': 'Service Center',
      'services': ['General Repairs', 'Oil Change', 'Brake Service', 'Diagnostics'],
      'rating': 4.5,
      'imageUrl': null,
      'openingHours': 'Mon-Sat: 8AM-6PM',
    },
    {
      'id': '2',
      'name': 'Moto Spares Hub',
      'category': 'Spare Parts',
      'description': 'Genuine motorcycle parts and accessories',
      'location': 'Kirinyaga Road, Nairobi',
      'latitude': -1.2864,
      'longitude': 36.8253,
      'contactPhone': '+254722345002',
      'contactEmail': 'sales@motospares.ke',
      'type': 'Parts Dealer',
      'services': ['Genuine Parts', 'Aftermarket Parts', 'Accessories', 'Helmets'],
      'rating': 4.7,
      'imageUrl': null,
      'openingHours': 'Mon-Sat: 8AM-7PM, Sun: 10AM-4PM',
    },
    {
      'id': '3',
      'name': 'Rapid Rescue Towing',
      'category': 'Towing',
      'description': '24/7 motorcycle towing and recovery services',
      'location': 'Mombasa Road, Nairobi',
      'latitude': -1.3167,
      'longitude': 36.8833,
      'contactPhone': '+254733345003',
      'contactEmail': 'rescue@rapidtowing.ke',
      'type': 'Emergency Service',
      'services': ['24/7 Towing', 'Roadside Assistance', 'Recovery', 'Jump Start'],
      'rating': 4.8,
      'imageUrl': null,
      'openingHours': '24/7',
    },
  ];

  static const List<Map<String, dynamic>> trips = [
    {
      'id': '1',
      'userId': 'current_user',
      'bikeId': '1',
      'name': 'Morning Commute',
      'route': 'Home to Office',
      'distance': 15.5,
      'durationMinutes': 35,
      'averageSpeed': 26.6,
      'maxSpeed': 60.0,
      'startTime': '2024-03-15T07:30:00.000Z',
      'endTime': '2024-03-15T08:05:00.000Z',
      'status': 'Completed',
      'locations': [
        {'latitude': -1.2921, 'longitude': 36.8219, 'timestamp': '2024-03-15T07:30:00.000Z'},
        {'latitude': -1.2864, 'longitude': 36.8253, 'timestamp': '2024-03-15T08:05:00.000Z'},
      ],
    },
    {
      'id': '2',
      'userId': 'current_user',
      'bikeId': '1',
      'name': 'Weekend Ride',
      'route': 'Nairobi to Thika',
      'distance': 45.0,
      'durationMinutes': 65,
      'averageSpeed': 41.5,
      'maxSpeed': 90.0,
      'startTime': '2024-03-16T09:00:00.000Z',
      'endTime': '2024-03-16T10:05:00.000Z',
      'status': 'Completed',
      'locations': [
        {'latitude': -1.2921, 'longitude': 36.8219, 'timestamp': '2024-03-16T09:00:00.000Z'},
        {'latitude': -1.0332, 'longitude': 37.0694, 'timestamp': '2024-03-16T10:05:00.000Z'},
      ],
    },
  ];

  static const List<Map<String, dynamic>> payments = [
    {
      'id': '1',
      'userId': 'current_user',
      'transactionId': 'TXN2024001234',
      'amount': 2500.0,
      'method': 'M-PESA',
      'status': 'Completed',
      'date': '2024-01-15T10:30:00.000Z',
      'purpose': 'Basic Membership Package',
      'reference': 'PKG001',
      'receiptUrl': null,
    },
    {
      'id': '2',
      'userId': 'current_user',
      'transactionId': 'TXN2024001567',
      'amount': 500.0,
      'method': 'M-PESA',
      'status': 'Completed',
      'date': '2024-03-20T14:15:00.000Z',
      'purpose': 'Event Registration - Nairobi City Ride',
      'reference': 'EVT001',
      'receiptUrl': null,
    },
    {
      'id': '3',
      'userId': 'current_user',
      'transactionId': 'TXN2024001890',
      'amount': 15000.0,
      'method': 'Bank Transfer',
      'status': 'Pending',
      'date': '2024-03-25T09:00:00.000Z',
      'purpose': 'Insurance Premium - Comprehensive',
      'reference': 'INS001',
      'receiptUrl': null,
    },
  ];

  static const List<Map<String, dynamic>> notifications = [
    {
      'id': '1',
      'userId': 'current_user',
      'title': 'Upcoming Event',
      'message': 'Nairobi City Ride starts in 2 days. Don\'t forget to register!',
      'type': 'Event',
      'isRead': false,
      'timestamp': '2024-03-25T10:00:00.000Z',
      'actionUrl': null,
      'metadata': {'eventId': '1'},
    },
    {
      'id': '2',
      'userId': 'current_user',
      'title': 'Payment Successful',
      'message': 'Your payment of KES 500.00 has been processed successfully.',
      'type': 'Payment',
      'isRead': true,
      'timestamp': '2024-03-20T14:20:00.000Z',
      'actionUrl': null,
      'metadata': {'paymentId': '2'},
    },
    {
      'id': '3',
      'userId': 'current_user',
      'title': 'Insurance Expiring Soon',
      'message': 'Your insurance policy expires in 30 days. Renew now to avoid lapse.',
      'type': 'Insurance',
      'isRead': false,
      'timestamp': '2024-03-24T08:00:00.000Z',
      'actionUrl': null,
      'metadata': {'insuranceId': '1'},
    },
  ];
}
